# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1706dd9b835635f4e1555c48bcdd577ec0648d1ad20ffdfd77431f8fcd39c0ca1a98a11f53d2a97a51df8dbd7d97d80338a3bf3f6a883823fdddaef313430b71

test:
  secret_key_base: 330ad13b51085d26f361b7cf6110d119a066382bba18218d87c13d027e089a64ac88a5fca7ee609f10549b1911ae9232c0dca92f911484549da6b75947a0d7ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
